[package]
name = "certificate_carver"
version = "0.1.3"
authors = ["David Cook <divergentdave@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.9"
copy_in_place = "0.2.0"
encoding = "0.2"
hex = "0.3"
lazy_static = "1.0"
regex = "0.2"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.8"
stringprep = "0.1.2"
unicode-normalization = "0.1"
untrusted = "0.6.2"
walkdir = "2"
zip = "0.3"
