[package]
name = "certificate_carver"
version = "0.1.7-alpha"
authors = ["David Cook <divergentdave@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10"
chrono = "0.4.7"
clap = "2.33.0"
copy_in_place = "0.2.0"
encoding = "0.2"
error-chain = "0.12.1"
hex = "0.3"
lazy_static = "1.0"
pdf = "0.7.0"
pdf_derive = "0.1.18"
rayon = "1.1.0"
regex = "1.1"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.8"
sled = "0.24.1"
stringprep = "0.1.2"
unicode-normalization = "0.1"
untrusted = "0.7.0"
walkdir = "2.2.9"
zip = "0.5"

[patch.crates-io]
pdf = { git = "https://github.com/pdf-rs/pdf", rev = "da89789fc50b68f3f97b161e87da1d08ccbc8e1f" }
pdf_derive = { git = "https://github.com/pdf-rs/pdf", rev = "da89789fc50b68f3f97b161e87da1d08ccbc8e1f" }
