[package]
name = "certificate_carver"
version = "0.1.0"
authors = ["David Cook <divergentdave@gmail.com>"]

[dependencies]
base64 = "0.9"
encoding = "0.2"
hex = "0.3"
lazy_static = "1.0"
openssl = "0.10"
regex = "0.2"
reqwest = "0.8"
ring = "0.14.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
untrusted = "0.6.2"  # Must match the version used by ring
walkdir = "2"
zip = "0.3"
