[package]
name = "certificate_carver"
version = "0.1.5"
authors = ["David Cook <divergentdave@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10"
chrono = "0.4.7"
copy_in_place = "0.2.0"
encoding = "0.2"
hex = "0.3"
lazy_static = "1.0"
regex = "1.1"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.8"
sled = "0.24.1"
stringprep = "0.1.2"
unicode-normalization = "0.1"
untrusted = "0.6.2"
walkdir = "2"
zip = "0.5"
