[package]
name = "certificate_carver"
version = "0.1.7-alpha"
authors = ["David Cook <divergentdave@gmail.com>"]
edition = "2018"
default-run = "certificate_carver"

[dependencies]
base64 = "0.10"
chrono = "0.4.9"
clap = "2.33.0"
encoding = "0.2"
hex = "0.3"
lazy_static = "1.4"
rayon = "1.2.0"
reqwest = "0.9"
serde_json = "1.0"
sha2 = "0.8"
sled = "0.24.1"
stringprep = "0.1.2"
unicode-normalization = "0.1"
untrusted = "0.7.0"
zip = "0.5"
walkdir = "2.2.9"

[dependencies.regex]
version = "1.3"
default-features = false
features = ["std", "perf"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
